# Generated by Django 2.0.6 on 2018-06-21 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bluemarble_app', '0002_auto_20180609_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='library',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='money',
            field=models.IntegerField(default=3000000),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='num',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='position',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='station',
            field=models.BooleanField(default=False),
        ),
    ]
